### ISSUE TITLE
asdf-protolint: Could not download https://github.com/yoheimuta/protolint/releases/download/v0.47.5/protolint_0.47.5_linux_x86_64.tar.gz

### ISSUE THREAD

**Issue by vorburger** [spencergilbert/asdf-protolint#37]
```shell
$ asdf plugin add protolint
$ asdf install protolint latest

* Downloading protolint release 0.47.5...
curl: (22) The requested URL returned error: 404
asdf-protolint: Could not download https://github.com/yoheimuta/protolint/releases/download/v0.47.5/protolint_0.47.5_linux_x86_64.tar.gz
```

It looks like this is because:

https://github.com/yoheimuta/protolint/releases/tag/v0.47.5

points to:

https://github.com/yoheimuta/protolint/releases/download/v0.47.5/protolint_0.47.5_linux_amd64.tar.gz

instead of:

https://github.com/yoheimuta/protolint/releases/download/v0.47.5/protolint_0.47.5_linux_x86_64.tar.gz

Note how apparently it changed from `x86_64` to `amd64`...

**Comment by spencergilbert** [comment]
Thanks for the report, it's very annoying when those change. I'll see if I can make a fix soon, but I'm also happy to accept a contribution.
